<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="green">
        <color rgba="0 1 0 1"/>
    </material>

    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_breadth" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.15"/>
    <xacro:property name="wheel_length" value="0.05"/>
    <xacro:property name="caster_wheel_radius" value="${wheel_radius/2}"/>


    <xacro:macro name="box_inertia" params="m l b h xyz rpy">
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}"/>
            <mass value="${m}"/>
            <inertia ixx="${(1/12)*m*(h*h + l*l)}" ixy="0" ixz="0"
                     iyy="${(1/12)*m*(b*b + l*l)}" iyz="0"
                     izz="${(1/12)*m*(b*b + h*h)}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="wheel_inertia" params="m l r xyz rpy">
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}"/>
            <mass value="${m}"/>
            <inertia ixx="${(1/12)*m*((3*r*r) + l*l)}" ixy="0" ixz="0" 
                     iyy="${(1/12)*m*((3*r*r) + l*l)}" iyz="0" 
                     izz="${(1/2)*m*r*r}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="m r xyz rpy">
        <inertial>
            <origin xyz="${xyz}" rpy="${rpy}"/>
            <mass value="${m}"/>
            <inertia ixx="${(2/5)*m*r*r}" ixy="0" ixz="0"
                     iyy="${(2/5)*m*r*r}" iyz="0"
                     izz="${(2/5)*m*r*r}"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="wheel_link" params="prefix y">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 ${y} 0" rpy="${pi/2} 0 0"/>  
                <material name="blue"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 ${y} 0" rpy="${pi/2} 0 0"/>
            </collision>
            <xacro:wheel_inertia m="1.0" l="${2*wheel_length}" r="${2*wheel_radius}" 
                                 xyz="0 ${y} 0" rpy="${pi/2} 0 0"/>
        </link>
    </xacro:macro>

</robot>